# Generated by Django 4.1.4 on 2022-12-27 17:47

from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encroachment_table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrt_id', models.CharField(max_length=50)),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active'), ('assigned', 'assigned'), ('follow_up', 'follow_up'), ('resolved', 'resolved'), ('audited', 'audited'), ('rejected', 'rejected')], default='active', max_length=100, no_check_for_status=True)),
                ('region', models.CharField(max_length=50)),
                ('subregion', models.CharField(max_length=50)),
                ('encrt_size', models.FloatField()),
                ('dist_coa', models.IntegerField()),
                ('criticality', model_utils.fields.StatusField(choices=[('high', 'high'), ('low', 'low')], default='high', max_length=100, no_check_for_status=True)),
            ],
        ),
    ]
